# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(670, 787)
        font = QtGui.QFont()
        font.setPointSize(14)
        Dialog.setFont(font)
        Dialog.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        Dialog.setStyleSheet("background-color: {#222222};")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(190, 100, 261, 351))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lineEdit_name = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.verticalLayout.addWidget(self.lineEdit_name)
        self.label_2 = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.lineEdit_surname = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.lineEdit_surname.setObjectName("lineEdit_surname")
        self.verticalLayout.addWidget(self.lineEdit_surname)
        self.label_3 = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.lineEdit_numertelefonu = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.lineEdit_numertelefonu.setObjectName("lineEdit_numertelefonu")
        self.verticalLayout.addWidget(self.lineEdit_numertelefonu)
        self.label_4 = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.lineEdit_pesel = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.lineEdit_pesel.setObjectName("lineEdit_pesel")
        self.verticalLayout.addWidget(self.lineEdit_pesel)
        self.checkBox_umowa = QtWidgets.QCheckBox(parent=self.verticalLayoutWidget)
        self.checkBox_umowa.setObjectName("checkBox_umowa")
        self.verticalLayout.addWidget(self.checkBox_umowa)
        self.pushButton_zapisz = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.pushButton_zapisz.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_zapisz.setObjectName("pushButton_zapisz")
        self.verticalLayout.addWidget(self.pushButton_zapisz)
        self.pushButton_zapisz_2 = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.pushButton_zapisz_2.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_zapisz_2.setObjectName("pushButton_zapisz_2")
        self.verticalLayout.addWidget(self.pushButton_zapisz_2)
        self.listWidget = QtWidgets.QListWidget(parent=Dialog)
        self.listWidget.setGeometry(QtCore.QRect(190, 470, 256, 111))
        self.listWidget.setObjectName("listWidget")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Imie"))
        self.label_2.setText(_translate("Dialog", "Nazwisko"))
        self.label_3.setText(_translate("Dialog", "Numer telefonu"))
        self.label_4.setText(_translate("Dialog", "Pasel"))
        self.checkBox_umowa.setText(_translate("Dialog", "Umowa o prace"))
        self.pushButton_zapisz.setText(_translate("Dialog", "Zapisz"))
        self.pushButton_zapisz_2.setText(_translate("Dialog", "Zapisz do pliku"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
